import { useEffect, useState } from 'react';
import Board from '../components/Board.jsx';
import HostControls from '../components/HostControls.jsx';
import { useGameEngine } from '../components/TurnEngine.jsx';
import { EVENT_META, EVENT_QUESTIONS, TEAM_COLORS } from '../data/constants.js';

const TEAM_LABELS = { 'team-1': 'One', 'team-2': 'Two', 'team-3': 'Three', 'team-4': 'Four', 'team-5': 'Five', 'team-6': 'Six' };
function Die({ value }) { return <div className="flex h-16 w-16 items-center justify-center rounded-2xl border-4 border-[#18233f] bg-white text-4xl font-black text-[#18233f] shadow-lg">{value || '🎲'}</div>; }

function ProjectorHud() {
  const { game } = useGameEngine();
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(timer); }, []);
  const teamCount = Object.keys(game.teams || {}).length;
  const positions = game.boardPositions || {};
  const config = game.phase === 'opening' ? game.opening : game.minigame;
  const question = EVENT_QUESTIONS.find((q) => q.id === config?.questionIds?.[config?.questionIndex]);
  const started = config?.startedAt?.toMillis?.() ?? config?.startedAt;
  const timeLeft = config && started ? Math.max(0, (config.timeLimit || 10) - (now - started) / 1000) : 0;
  return <>
    <div className="pointer-events-none absolute inset-x-0 top-0 z-40 p-5 md:p-7"><div className="flex items-start justify-between gap-5"><div className="rounded-[1.5rem] border-4 border-[#18233f] bg-[#fff8e7]/95 px-5 py-3 shadow-xl"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#ff8c4d]">{EVENT_META.title}</p><h1 className="font-display text-2xl md:text-4xl text-[#18233f]">{EVENT_META.tagline}</h1></div><div className="rounded-[1.5rem] border-4 border-[#18233f] bg-[#18233f]/95 px-5 py-3 text-right text-white shadow-xl"><p className="text-[10px] font-black uppercase tracking-[0.25em] text-white/60">{game.phase === 'lobby' ? 'LOBBY' : game.phase === 'finished' ? 'FINISH' : `ROUND ${game.round}`}</p><p className="font-display text-2xl md:text-3xl">{teamCount}/6 TEAMS</p></div></div></div>
    {game.phase === 'lobby' && <div className="pointer-events-none absolute inset-0 z-30 flex items-center justify-center p-8"><div className="rounded-[2.5rem] border-4 border-[#18233f] bg-[#fff8e7]/96 px-10 py-8 text-center shadow-2xl"><div className="mb-4 text-6xl">🎮</div><p className="text-xs font-black uppercase tracking-[0.3em] text-[#ff8c4d]">Get ready</p><h2 className="mt-2 font-display text-5xl text-[#18233f]">Waiting for players</h2><p className="mt-3 text-xl font-black text-[#687187]">{teamCount} of 6 teams joined</p></div></div>}
    {(game.phase === 'opening' || game.phase === 'minigame') && question && <div className="pointer-events-none absolute inset-x-0 bottom-6 z-40 mx-auto w-[min(92%,1000px)]"><div className="rounded-[2rem] border-4 border-[#18233f] bg-[#fff8e7]/97 p-5 shadow-2xl"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-[#ff8c4d]">{game.phase === 'opening' ? 'OPENING RAPID SHOT' : game.minigame?.label}</p><p className="mt-1 text-xl md:text-3xl font-black text-[#18233f]">{question.prompt}</p></div><div className={`shrink-0 rounded-2xl border-4 border-[#18233f] px-4 py-2 text-center ${timeLeft <= 3 ? 'bg-[#ff4d4d] text-white' : 'bg-white text-[#18233f]'}`}><p className="text-[10px] font-black uppercase">Time</p><p className="text-3xl font-black tabular-nums">{timeLeft.toFixed(1)}s</p></div></div></div></div>}
    {game.phase === 'playing' && <div className="pointer-events-none absolute inset-x-0 bottom-6 z-40 mx-auto flex w-[min(92%,1000px)] items-end justify-between gap-4"><div className="rounded-[2rem] border-4 border-[#18233f] bg-[#fff8e7]/97 px-6 py-4 shadow-2xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#ff8c4d]">CURRENT TURN</p><p className="font-display text-4xl text-[#18233f]">TEAM {TEAM_LABELS[game.activeTeamId]}</p><p className="font-black text-[#687187]">Tile {(positions[game.activeTeamId] ?? 0) + 1} / 67</p></div>{game.dice?.status === 'rolled' && <div className="rounded-[2rem] border-4 border-[#18233f] bg-[#fff8e7]/97 p-4 shadow-2xl"><p className="mb-2 text-center text-xs font-black uppercase tracking-wider text-[#687187]">Last roll</p><div className="flex gap-2"><Die value={game.dice.die1} /><Die value={game.dice.die2} /></div><p className="mt-2 text-center font-black text-[#18233f]">TOTAL {game.dice.total}</p></div>}</div>}
    {(game.phase === 'opening-results' || game.phase === 'minigame-results' || game.phase === 'round-transition' || game.phase === 'turn-order') && <div className="pointer-events-none absolute inset-0 z-30 flex items-center justify-center p-8"><div className="w-[min(90%,720px)] rounded-[2.5rem] border-4 border-[#18233f] bg-[#fff8e7]/97 p-8 shadow-2xl"><p className="text-center text-xs font-black uppercase tracking-[0.25em] text-[#ff8c4d]">{game.phase === 'opening-results' || game.phase === 'turn-order' ? 'OPENING ORDER' : 'NEXT ROUND ORDER'}</p><h2 className="mt-2 text-center font-display text-5xl text-[#18233f]">{game.phase === 'opening-results' || game.phase === 'turn-order' ? `Team ${TEAM_LABELS[game.turnOrder?.[0]]} starts!` : 'Who rolls first?'}</h2><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-3">{(game.turnOrder || game.rankings?.map((r) => r.teamId) || []).map((id, index) => <div key={id} className={`rounded-2xl border-4 p-4 text-center ${index === 0 ? 'border-[#ff8c4d] bg-[#fff0e5]' : 'border-[#18233f]/10 bg-white'}`}><div className="mx-auto mb-2 h-7 w-7 rounded-full border-2 border-[#18233f]" style={{ background: TEAM_COLORS[Number(id.split('-')[1]) - 1] }} /><p className="font-black text-[#18233f]">{index + 1}. Team {TEAM_LABELS[id]}</p></div>)}</div></div></div>}
    {game.phase === 'finished' && <div className="pointer-events-none absolute inset-0 z-50 flex items-center justify-center p-8"><div className="w-[min(90%,760px)] rounded-[3rem] border-4 border-[#18233f] bg-[#fff8e7]/98 p-10 text-center shadow-2xl"><div className="text-8xl">🏆</div><p className="mt-3 text-sm font-black uppercase tracking-[0.3em] text-[#ff8c4d]">GAME COMPLETE</p><h2 className="mt-2 font-display text-6xl text-[#18233f]">TEAM {TEAM_LABELS[game.winner]} WINS!</h2><p className="mt-4 text-xl font-black text-[#687187]">First to reach the finish tile</p><div className="mt-7 grid grid-cols-3 gap-3">{(game.rankings || []).slice(0, 3).map((r) => <div key={r.teamId} className="rounded-2xl border-4 border-[#18233f]/10 bg-white p-4"><p className="text-3xl">{['🥇','🥈','🥉'][r.position - 1]}</p><p className="font-black text-[#18233f]">Team {TEAM_LABELS[r.teamId]}</p></div>)}</div></div></div>}
  </>;
}

export default function HostPage() {
  const { game } = useGameEngine();
  const [controlsOpen, setControlsOpen] = useState(true);
  useEffect(() => { setControlsOpen(game.phase === 'lobby'); }, [game.phase]);
  return <div className="relative h-screen w-full overflow-hidden bg-[#dbe8b6]"><main className="absolute inset-0"><Board /></main><ProjectorHud /><button type="button" onClick={() => setControlsOpen((open) => !open)} className="absolute right-5 top-5 z-[70] rounded-full border-4 border-[#18233f] bg-[#fff8e7] px-4 py-2 text-xs font-black text-[#18233f] shadow-xl">{controlsOpen ? 'Hide Host Controls' : 'Host Controls'}</button>{controlsOpen && <aside className="absolute right-5 top-20 z-[60] w-[340px] max-h-[calc(100vh-6rem)] overflow-y-auto rounded-[1.5rem] border-4 border-[#18233f] bg-[#f7f2df]/97 p-3 shadow-2xl"><HostControls /></aside>}</div>;
}
