import { useEffect } from 'react';
import { useGameEngine } from './TurnEngine.jsx';
import { EVENT_QUESTIONS, TEAM_COLORS } from '../data/constants.js';
const TEAM_LABELS = { 'team-1': 'One', 'team-2': 'Two', 'team-3': 'Three', 'team-4': 'Four', 'team-5': 'Five', 'team-6': 'Six' };
function TeamRow({ teamId, rank, score, position, active }) { const color = TEAM_COLORS[Number(teamId.split('-')[1]) - 1]; return <div className={`flex items-center gap-3 rounded-2xl border-2 px-3 py-3 ${active ? 'border-[#ff8c4d] bg-[#fff4e8]' : 'border-[#18233f]/10 bg-white'}`}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#18233f] text-sm font-black text-white">{rank}</div><span className="h-3 w-3 rounded-full" style={{ background: color }} /><div className="min-w-0 flex-1"><p className="truncate font-black text-[#18233f]">Team {TEAM_LABELS[teamId]}</p><p className="text-xs font-semibold text-[#7a8395]">{score ?? 0} pts{position !== undefined ? ` • Tile ${position + 1}` : ''}</p></div>{active && <span className="rounded-full bg-[#ff8c4d] px-2 py-1 text-[10px] font-black uppercase text-white">Turn</span>}</div>; }
function QuestionPanel({ game }) {
  let config = null; let label = '';
  if (game.phase === 'opening') { config = game.opening; label = 'OPENING'; }
  else if (game.phase === 'minigame') { config = game.minigame; label = (game.minigame?.label || 'Mini-game').toUpperCase(); }
  else if (game.phase === 'challenge') { config = { questionIds: [game.challenge?.questionId], questionIndex: 0, questionCount: 1, timeLimit: game.challenge?.timeLimit }; label = 'CHALLENGE'; }
  const question = config ? EVENT_QUESTIONS.find((q) => q.id === config.questionIds?.[config.questionIndex]) : null;
  if (!config) return null;
  return <section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-[#18233f] px-3 py-1 text-xs font-black text-white">{label}</span><span className="font-black text-[#ff8c4d]">{config.timeLimit}s</span></div><p className="mt-4 font-black text-[#18233f]">{question?.prompt}</p></section>;
}
export default function HostControls() {
  const { game, gameLoaded, gameExists, initLobby, startGame, advanceQuestion, beginBoard, startInitialRound, prepareNextRound, startNextRound, submitChallengeAnswer, resetForNewGame } = useGameEngine();
  useEffect(() => { if (gameLoaded && !gameExists) initLobby().catch(console.error); }, [gameLoaded, gameExists, initLobby]);
  useEffect(() => { if (!['opening', 'minigame'].includes(game.phase)) return undefined; const config = game.phase === 'opening' ? game.opening : game.minigame; const started = config?.startedAt?.toMillis?.() ?? config?.startedAt ?? Date.now(); const delay = Math.max(0, started + (config?.timeLimit || 10) * 1000 - Date.now()) + 200; const timer = setTimeout(() => advanceQuestion().catch(console.error), delay); return () => clearTimeout(timer); }, [game.phase, game.opening?.questionIndex, game.opening?.startedAt, game.minigame?.questionIndex, game.minigame?.startedAt, game.opening?.timeLimit, game.minigame?.timeLimit, advanceQuestion]);
  useEffect(() => { if (game.phase !== 'opening-results') return undefined; const timer = setTimeout(() => beginBoard().catch(console.error), 3500); return () => clearTimeout(timer); }, [game.phase, beginBoard]);
  useEffect(() => { if (game.phase !== 'turn-order') return undefined; const timer = setTimeout(() => startInitialRound().catch(console.error), 3000); return () => clearTimeout(timer); }, [game.phase, startInitialRound]);
  useEffect(() => { if (game.phase !== 'minigame-results') return undefined; const timer = setTimeout(() => prepareNextRound().catch(console.error), 3500); return () => clearTimeout(timer); }, [game.phase, prepareNextRound]);
  useEffect(() => { if (game.phase !== 'round-transition') return undefined; const timer = setTimeout(() => startNextRound().catch(console.error), 3000); return () => clearTimeout(timer); }, [game.phase, startNextRound]);
  useEffect(() => { if (game.phase !== 'challenge' || !game.challenge || game.challenge.resolved) return undefined; const started = game.challenge.startedAt?.toMillis?.() ?? game.challenge.startedAt ?? Date.now(); const delay = Math.max(0, started + (game.challenge.timeLimit || 15) * 1000 - Date.now()) + 200; const timer = setTimeout(() => submitChallengeAnswer(game.challenge.teamId, 0, true).catch(console.error), delay); return () => clearTimeout(timer); }, [game.phase, game.challenge?.teamId, game.challenge?.startedAt, game.challenge?.resolved, game.challenge?.timeLimit, submitChallengeAnswer]);
  const joinedTeams = Object.keys(game.teams || {}); const positions = game.boardPositions || {}; const scores = game.minigame?.scores || game.opening?.scores || {}; const leaderboard = [...(game.turnOrder || joinedTeams)].sort((a, b) => (positions[b] ?? 0) - (positions[a] ?? 0));
  if (!gameLoaded) return <div className="p-4 text-center font-bold">Connecting…</div>;
  if (game.phase === 'lobby') return <div className="space-y-4"><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-5"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#7a8395]">Lobby</p><h2 className="font-display text-3xl text-[#18233f]">Players ready?</h2></div><span className="rounded-full bg-[#18233f] px-3 py-1 text-sm font-black text-white">{joinedTeams.length} / 6</span></div><div className="grid grid-cols-2 gap-2">{Object.keys(TEAM_LABELS).map((id) => <div key={id} className={`rounded-xl border-2 px-3 py-3 font-black ${game.teams?.[id] ? 'border-[#4dff79] bg-[#effff2] text-[#18233f]' : 'border-[#18233f]/10 bg-gray-50 text-gray-400'}`}>{game.teams?.[id] ? '✓ ' : ''}Team {TEAM_LABELS[id]}</div>)}</div></section><button onClick={startGame} disabled={!joinedTeams.length} className="w-full rounded-2xl border-4 border-[#18233f] bg-[#ff4d4d] px-5 py-5 text-lg font-black text-white shadow-md disabled:opacity-40">🎮 START GAME</button><p className="text-center text-xs font-bold text-[#7a8395]">3 opening rapid shots determine the first dice order.</p></div>;
  if (game.phase === 'opening') return <div className="space-y-4"><QuestionPanel game={game} /><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-4"><p className="mb-3 text-xs font-black uppercase tracking-wider text-[#7a8395]">Live opening scores</p><div className="space-y-2">{Object.entries(game.opening?.scores || {}).sort(([, a], [, b]) => b - a).map(([id, score], index) => <TeamRow key={id} teamId={id} rank={index + 1} score={score} />)}</div></section></div>;
  if (game.phase === 'opening-results' || game.phase === 'turn-order') return <div className="space-y-4"><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-5 text-center"><p className="text-xs font-black uppercase tracking-wider text-[#ff8c4d]">Opening order</p><h2 className="mt-1 font-display text-3xl text-[#18233f]">Team {TEAM_LABELS[game.turnOrder?.[0]]} first</h2><p className="mt-2 text-sm font-semibold text-[#7a8395]">Starting the 2-dice race…</p></section>{(game.turnOrder || []).map((id, index) => <TeamRow key={id} teamId={id} rank={index + 1} score={game.opening?.scores?.[id] || 0} />)}</div>;
  if (game.phase === 'minigame') return <div className="space-y-4"><QuestionPanel game={game} /><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-4"><p className="mb-3 text-xs font-black uppercase tracking-wider text-[#7a8395]">Next-round race</p><div className="space-y-2">{Object.entries(game.minigame?.scores || {}).sort(([, a], [, b]) => b - a).map(([id, score], index) => <TeamRow key={id} teamId={id} rank={index + 1} score={score} />)}</div></section></div>;
  if (game.phase === 'minigame-results' || game.phase === 'round-transition') return <div className="space-y-4"><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-5 text-center"><p className="text-xs font-black uppercase tracking-wider text-[#ff8c4d]">Round {game.round} complete</p><h2 className="mt-1 font-display text-3xl text-[#18233f]">Next dice order</h2></section>{(game.rankings || []).map((r) => <TeamRow key={r.teamId} teamId={r.teamId} rank={r.position} score={game.minigame?.scores?.[r.teamId] || 0} position={positions[r.teamId] ?? 0} />)}</div>;
  if (game.phase === 'finished') return <div className="space-y-4"><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-5 text-center"><div className="text-5xl">🏆</div><p className="mt-2 text-xs font-black uppercase tracking-wider text-[#ff8c4d]">Winner</p><h2 className="font-display text-4xl text-[#18233f]">Team {TEAM_LABELS[game.winner]}</h2></section>{(game.rankings || []).map((r) => <TeamRow key={r.teamId} teamId={r.teamId} rank={r.position} position={positions[r.teamId] ?? 0} />)}<button onClick={() => resetForNewGame().catch(console.error)} className="w-full rounded-2xl border-4 border-[#18233f] bg-[#4d79ff] px-5 py-4 font-black text-white">NEW GAME</button></div>;
  if (game.phase === 'challenge') return <div className="space-y-4"><QuestionPanel game={game} /><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-4 text-center"><p className="text-xs font-black uppercase tracking-wider text-[#7a8395]">Challenge</p><p className="mt-1 font-display text-2xl text-[#18233f]">Team {TEAM_LABELS[game.challenge?.teamId]} answers</p><p className="mt-1 text-sm font-semibold text-[#7a8395]">Win +3 tiles · Lose −5 tiles</p></section></div>;
  return <div className="space-y-4"><section className="rounded-2xl border-2 border-[#18233f]/10 bg-white p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#7a8395]">Round {game.round}</p><h2 className="font-display text-3xl text-[#18233f]">2-Dice Race</h2></div><span className="rounded-full bg-[#4dff79] px-3 py-1 text-xs font-black text-[#18233f]">LIVE</span></div><div className="mt-4 space-y-2">{leaderboard.map((teamId, index) => <TeamRow key={teamId} teamId={teamId} rank={index + 1} position={positions[teamId] ?? 0} active={game.activeTeamId === teamId} />)}</div></section><section className="rounded-2xl bg-[#18233f] p-4 text-center text-white"><p className="text-xs font-black uppercase tracking-wider text-white/60">Current turn</p><p className="mt-1 font-display text-3xl">Team {TEAM_LABELS[game.activeTeamId]}</p><p className="mt-1 text-sm font-bold text-white/70">Players roll both dice from their own device.</p></section></div>;
}
