import boardTiles from '../data/boardTiles.json';
import { TILE_TYPES, TOKEN_COLORS } from '../data/constants.js';

const points = Array.from({ length: 67 }, (_, i) => {
  const t = i / 66;
  const angle = t * Math.PI * 6.2;
  const radius = 300 - t * 245;
  return { x: 400 + Math.cos(angle) * radius, y: 300 + Math.sin(angle) * radius * 0.62 };
});
function style(tile){const base={width:52,height:52,borderRadius:14,display:'grid',placeItems:'center',fontSize:10,fontWeight:900,position:'absolute',border:'3px solid #18233f',boxShadow:'0 4px 10px rgba(24,35,63,.18)'};const map={start:['#4dff79','#18233f'],finish:['#ff5555','#fff'],bonus:['#ffea4d','#18233f'],penalty:['#ff8c4d','#18233f'],challenge:['#4d79ff','#fff'],normal:['#fffdf5','#18233f']};const [background,color]=map[tile?.type]||map.normal;return {...base,background,color};}
export default function MultiplayerBoard({boardPositions={},players={}}){return <div className="relative w-full overflow-hidden rounded-[2rem] border-4 border-[#18233f] bg-[#bde3ee] shadow-2xl" style={{height:620}}><div className="absolute inset-0 opacity-50" style={{background:'radial-gradient(circle at 20% 20%, white 0 4%, transparent 5%), radial-gradient(circle at 80% 30%, white 0 3%, transparent 4%)',backgroundSize:'140px 120px'}}/>{points.map((p,i)=>{const tile=boardTiles[i]||{type:'normal'};const tokens=Object.entries(boardPositions).filter(([,pos])=>pos===i);return <div key={i} style={{...style(tile),left:p.x-26,top:p.y-26}}><span>{tile.type===TILE_TYPES.START?'START':tile.type===TILE_TYPES.FINISH?'FINISH':tile.type===TILE_TYPES.BONUS?`+${tile.move||0}`:tile.type===TILE_TYPES.PENALTY?`${tile.move||0}`:tile.type===TILE_TYPES.CHALLENGE?'?':i}</span>{tokens.map(([id,j])=>{const ids=Object.keys(players);const color=TOKEN_COLORS[Math.max(0,ids.indexOf(id))%TOKEN_COLORS.length];return <span key={id} title={players[id]?.name} className="absolute h-8 w-8 rounded-full border-4 border-[#18233f] grid place-items-center text-white text-[10px] font-black" style={{background:color,transform:`translate(${(j%3-1)*14}px,${(j%2)*14}px)`}}>{(ids.indexOf(id)+1)}</span>;})}</div>})}<div className="absolute left-5 top-5 rounded-2xl border-4 border-[#18233f] bg-[#fff8e7]/95 px-4 py-3"><p className="text-[10px] font-black uppercase tracking-widest text-[#ff8c4d]">Adventure Board</p><p className="font-black text-[#18233f]">67 tiles • 7 players</p></div></div>}
